### ISSUE TITLE
Snote importer

### ISSUE THREAD

**Issue by Invictaz** [MuStAPro/snbtotxt#1]
Can you develop an importer?
For example .CSV into .SNB or .TXT into SNB?

So the other way around.
Newer S-Note files are stored in .SPB format. Can you support that too?

Thanks.

**Comment by MuStAPro** [comment]
Hello Invicatz,

I have been inactive in Github recently, but I am willing to develop an imported if I was given the .SPB and .SNB files again, since I don't own Samsung S-Note myself.

Mustafa.
